classdef Chemistry
    % Some data about chemical groups
    % Physical properties such as Molecular Weight
    
    properties (Constant)
        Groups = struct(...
            'CH2', struct('Mw', 14),...
            'Me', struct('Mw', 15),...
            'Fmoc', struct('Mw', 259),...
            'NHFmoc', struct('Mw', 259 - 35 + 14 + 1),...
            'COOH', struct('Mw', 12+2*16+1),...
            'NHS', struct('Mw', 115),...
            'COONHS', struct('Mw', 99 + 12+2*16));
        
        % Bond Lengths
        BondLengths = struct(...
            'CC_sp3', 0.15,...
            'CO_sp3', 0.14,...
            'CN_amine', 0.14,...
            'CN_amide', 0.13);
    end
    
    methods (Static)
        function mw = Mw(arr)
            mw = 0;
            for i = 1:length(arr)
                mw = mw + arr(i).Mw;
            end
        end
    end
    
end

