sinfo = ForSDAT.Sim.SimInfo();
sim = ForSDAT.Sim.CurveSimulator(sinfo, ...
        [ForSDAT.Sim.DistanceSimulator(sinfo), ...
         ForSDAT.Sim.ContactDomainSimulator(sinfo), ...
         ForSDAT.Sim.BaselineSimulator(sinfo), ...
         ForSDAT.Sim.NoiseSimulator(sinfo),...
         ForSDAT.Sim.NonSpecificInteractionSimulator(sinfo, 'LoadingLengthMu', 50, 'LoadingLengthSig', 25)]);
n = 1;

for i = n:-1:1
    fdc(i) = sim.simulate(1,1,i);
    fdc.plotCurve();
end

% save('simulatedCurves.mat', 'fdc');